#!/usr/bin/env node

var argv = require('yargs').argv;
var server = require('./lib/server.js');
var cards = require('./lib/cards.js');
var open = require('open');




console.log("  __  __             _        __  _  __   ____            _     _        \n |  \\/  |           (_)      / /\\| |/\\ \\ |  _ \\          | |   | |       \n | \\  / | __ _  __ _ _  ___ / /\\ ` ' /\\ \\| |_) |_   _  __| | __| |_   _  \n | |\\/| |/ _` |/ _` | |/ __< <|_     _|> >  _ <| | | |/ _` |/ _` | | | | \n | |  | | (_| | (_| | | (__ \\ \\/ , . \\/ /| |_) | |_| | (_| | (_| | |_| | \n |_|  |_|\\__,_|\\__, |_|\\___| \\_\\/|_|\\/_/ |____/ \\__,_|\\__,_|\\__,_|\\__, | \n                __/ |                                              __/ | \n               |___/                                              |___/  ");

opts = loadOptions();

if(opts.debug) console.log("Running in debug mode.");


var models = {}

cards(opts, function(cards){
    models["cards"] = cards;

    loadDecks(opts, models["cards"],  function(decks){
        models["decks"] = decks;

        loadCollection(opts, models["cards"], function(collection){
            models["collection"] = collection;

            finishedPreload();
        });
    });
});

function finishedPreload(){
    console.log("Starting web server.");
    server(opts, models); 
    ready(opts);
}

function loadOptions(){

    var opts = {
        version: "0.1",
        debug: argv.debug || false,
        host: argv.host || "localhost",
        port: argv.port || 8000,
        
        //if the host is 0.0.0.0 we should set the url to localhost
        url: (argv.host !== undefined && argv.host!=="0.0.0.0")?argv.host:"localhost",

        // should we open a browser
        headeed: argv.headed || false,
        data: argv.data || "./data",
        cache: argv.cache || "./cache",

        //how often we should make a checkpoint automatically
        checkpoint: argv.checkpoint || 60
    }

    return opts;
}

function loadDecks(opts, cards, callback){
    require('./lib/decks.js')(opts, cards, callback);
}

function loadCollection(opts, cards, callback){
    require('./lib/collection.js')(opts, cards, callback);
}

function ready(opts){
    if(opts.headed){
        console.log("Launching browser."); 
        open("http://" + url + ":" + port)
    }
}
